GET http://localhost:8880/ebook/list?page=3&size=2

###

GET http://localhost:8880/ebook/list?name=Spring

###ptrt form表单方式的提交

POST http://localhost:8880/ebook/save
Content-Type: application/x-www-form-urlencoded

id=1&name=springboot

###ptr json方式提交
POST http://localhost:8880/ebook/save
Content-Type: application/json

{"name":"test","description": "test test"}

###
DELETE http://localhost:8880/ebook/delete/373822393472389120

###
GET http://localhost:8880/doc/find-content/2
Accept: application/json

###

POST http://localhost:8880/doc/save
Content-Type: application/json

{"ebookId": 1, "parent": 1, "name": "test1", "sort": 1, "content": "test1"}

###