GET http://localhost:8880/user/list
Accept: application/json

###

POST http://localhost:8880/user/save
Content-Type: application/json

{"loginName":"test3","name":"测试2","password": "123456ABC"}

###

POST http://localhost:8880/user/reset-password
Content-Type: application/json

{"id": 1, "password": "123ABC"}

###
POST http://localhost:8880/user/login
Content-Type: application/json

{"loginName":"test", "password":"123ABC"}

###

GET http://localhost:8880/redis/set/123/test
Accept: application/json

###

GET http://localhost:8880/redis/get/123
Accept: application/json

###
